export const AR_KEYWORD = {
    "???" : "as",
    "صحيح": "true",
    "غير_صحيح": "false",
    "عندما": "when",
    "حيث": "where",
    "احضر": "use",
    "عرف" : "let",
    "ثابت": "const",
    "متغير": "var",
    "دل": "fn",
    "نوع": "type",
    "سمة": "trait",
    "???": "impl",
    "رد": "return",
    "نفذ" : "do",
}

export const EN_KEYWORD = { 
    "as" : "???",
    "true" : "صحيح",
    "false" : "غير_صحيح",
    "when" : "عندما",
    "where" : "حيث",
    "use" : "احضر",
    "let" : "عرف",
    "const" : "ثابت",
    "var" : "متغير",
    "fn" : "دل",
    "type" : "نوع",
    "trait" : "سمة",
    "impl" : "???",
    "return" : "رد",
    "do" : "نفذ",
}